name: Build and Test Spring Boot

# События, на которые запускается workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Форсируем Node.js 24, чтобы не было ошибки exit code 127
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    # PostgreSQL как сервис
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Сборка Spring Boot JAR
      - name: Build Spring Boot JAR
        run: ./gradlew clean bootJar

      # Проверка наличия JAR
      - name: Check JAR
        run: ls build/libs/

      # Тест доступности API без Docker Compose
      - name: Test application
        run: |
          echo "Тестируем API /items через Java процесс"
          java -jar build/libs/demo-0.0.1-SNAPSHOT.jar &
          sleep 20
          curl -f http://localhost:8080/items || exit 1
