name: Build and Test Docker Lab

on:
  push:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres-db:
        image: postgres:15
        env:
          POSTGRES_DB: some_name
          POSTGRES_USER: some_user
          POSTGRES_PASSWORD: some_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U some_user -d some_name"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Spring Boot JAR
        # Добавили --stacktrace, чтобы в логах было видно точную причину ошибки
        run: ./gradlew bootJar --stacktrace

      - name: Prepare JAR for Docker
        run: cp build/libs/*.jar backend.jar

      - name: Run Docker Compose
        env:
          DB_NAME: some_name
          DB_USER: some_user
          DB_PASSWORD: some_password
          DB_HOST: postgres-db
        run: docker-compose up -d --build

      - name: Verify Application
        run: |
          sleep 30
          docker ps
          curl -v http://localhost:8080/items || echo "App is starting..."
